### ISSUE TITLE
WTForms import error on TextField

### ISSUE THREAD

**Issue by satanb4** [realpython/flask-boilerplate#56]
There is an error when running app.py:-
```
Traceback (most recent call last):
  File "D:\Projects\Technothon 2022\HelpR\app.py", line 9, in <module>
    from forms import *
  File "D:\Projects\Technothon 2022\HelpR\forms.py", line 2, in <module>
    from wtforms import TextField, PasswordField
ImportError: cannot import name 'TextField' from 'wtforms' (D:\Projects\Technothon 2022\HelpR\venv\lib\site-packages\wtforms\__init__.py)
```
This is caused in python==3.10.1 and WTForms 3.0.1 having deprecated the TextField method
This can be resolved by either pinning WTForms==2.3.3 in `requirements.txt` or updating from `TextField` to `StringField` in forms.py
Please advice which method we would like to use, I can perform the necessary change to rectify this issue.

**Comment by axyklee** [comment]
I made a pull request to update everything to 2022-level. [here](https://github.com/realpython/flask-boilerplate/pull/58) It includes this update. If anyone's interested.

- Switched anything that can be cdn'd to CDNJS, including Bootstrap, Font Awesome, and jQuery.
- Updated to Bootstrap 5.1.3 and Fontawesome 6.1.1
- Removed Fabric
- Removed Modernizr and the useless Google Analytics (if you can write a Flask app, you could probably configure Google Analytics)
- Pre-configured Flask-SQLAlchemy, Flask-Login, Flask-WTF, and Flask-Admin for you.
- This implies that this has a full-fledged user management system already configured for you.
